# syntax=docker/dockerfile:1

FROM node:22-alpine@sha256:16e22a550f3863206a3f701448c45f7912c6896a62de43add43bb9c86130c3e2 AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-alpine@sha256:16e22a550f3863206a3f701448c45f7912c6896a62de43add43bb9c86130c3e2 AS builder
WORKDIR /app
ARG SITE_URL=https://nox.cloud-it.com.ar
ARG SITE_INDEXABLE=true
ARG NEXT_PUBLIC_MEDIA_PUBLIC_URL=
ARG NEXT_PUBLIC_MEDIA_TRANSFORM_URL=
ARG NEXT_PUBLIC_MEDIA_TENANT=nox
ENV SITE_URL=$SITE_URL
ENV SITE_INDEXABLE=$SITE_INDEXABLE
ENV NEXT_PUBLIC_MEDIA_PUBLIC_URL=$NEXT_PUBLIC_MEDIA_PUBLIC_URL
ENV NEXT_PUBLIC_MEDIA_TRANSFORM_URL=$NEXT_PUBLIC_MEDIA_TRANSFORM_URL
ENV NEXT_PUBLIC_MEDIA_TENANT=$NEXT_PUBLIC_MEDIA_TENANT
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:22-alpine@sha256:16e22a550f3863206a3f701448c45f7912c6896a62de43add43bb9c86130c3e2 AS runner
WORKDIR /app
ARG SITE_URL=https://nox.cloud-it.com.ar
ARG SITE_INDEXABLE=true
ARG NEXT_PUBLIC_MEDIA_PUBLIC_URL=
ARG NEXT_PUBLIC_MEDIA_TRANSFORM_URL=
ARG NEXT_PUBLIC_MEDIA_TENANT=nox
ENV NODE_ENV=production
ENV SITE_URL=$SITE_URL
ENV SITE_INDEXABLE=$SITE_INDEXABLE
ENV NEXT_PUBLIC_MEDIA_PUBLIC_URL=$NEXT_PUBLIC_MEDIA_PUBLIC_URL
ENV NEXT_PUBLIC_MEDIA_TRANSFORM_URL=$NEXT_PUBLIC_MEDIA_TRANSFORM_URL
ENV NEXT_PUBLIC_MEDIA_TENANT=$NEXT_PUBLIC_MEDIA_TENANT
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
