-- migrate:up

CREATE TABLE product_categories (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug        text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name        text NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 100),
    description text NOT NULL DEFAULT '',
    sort_order  int NOT NULL DEFAULT 0,
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

INSERT INTO product_categories (slug, name, description)
VALUES ('cuidado-personal', 'Cuidado personal', 'Productos para el cuidado diario.')
ON CONFLICT (slug) DO NOTHING;

ALTER TABLE products
    ADD COLUMN slug text,
    ADD COLUMN description text NOT NULL DEFAULT '',
    ADD COLUMN short_description text NOT NULL DEFAULT '',
    ADD COLUMN category_id uuid REFERENCES product_categories(id) ON DELETE SET NULL,
    ADD COLUMN image_url text,
    ADD COLUMN gallery jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(gallery) = 'array'),
    ADD COLUMN featured boolean NOT NULL DEFAULT false,
    ADD COLUMN sort_order int NOT NULL DEFAULT 0,
    ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

UPDATE products
SET slug = lower(trim(both '-' FROM regexp_replace(sku, '[^a-zA-Z0-9]+', '-', 'g'))),
    category_id = (SELECT id FROM product_categories WHERE slug = 'cuidado-personal')
WHERE slug IS NULL;

UPDATE products
SET slug = 'producto-' || substr(id::text, 1, 8)
WHERE slug = '';

ALTER TABLE products
    ALTER COLUMN slug SET NOT NULL,
    ADD CONSTRAINT products_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$');

CREATE UNIQUE INDEX products_slug_unique ON products (slug);
CREATE INDEX products_shop_listing_idx
    ON products (active, category_id, featured DESC, sort_order, name);
CREATE INDEX products_shop_search_idx
    ON products USING gin (to_tsvector('simple', name || ' ' || description || ' ' || sku));

CREATE TABLE shopping_carts (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash     bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    customer_email text,
    status         text NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active', 'converted', 'abandoned', 'expired')),
    currency       char(3) NOT NULL DEFAULT 'ARS',
    expires_at     timestamptz NOT NULL DEFAULT now() + interval '30 days',
    last_activity  timestamptz NOT NULL DEFAULT now(),
    converted_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX shopping_carts_recovery_idx
    ON shopping_carts (status, last_activity)
    WHERE status = 'active';

CREATE TABLE shopping_cart_items (
    cart_id    uuid NOT NULL REFERENCES shopping_carts(id) ON DELETE CASCADE,
    product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity   int NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (cart_id, product_id)
);

CREATE TABLE shop_orders (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number        bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    cart_id             uuid UNIQUE REFERENCES shopping_carts(id) ON DELETE SET NULL,
    idempotency_hash    bytea NOT NULL UNIQUE CHECK (octet_length(idempotency_hash) = 32),
    customer_name       text NOT NULL CHECK (length(trim(customer_name)) BETWEEN 2 AND 120),
    customer_email      text NOT NULL,
    customer_phone      text NOT NULL,
    status              text NOT NULL DEFAULT 'confirmed'
                        CHECK (status IN ('pending', 'confirmed', 'ready', 'completed', 'cancelled')),
    payment_method      text NOT NULL DEFAULT 'pay_at_store'
                        CHECK (payment_method IN ('pay_at_store', 'mercado_pago')),
    payment_status      text NOT NULL DEFAULT 'unpaid'
                        CHECK (payment_status IN ('unpaid', 'pending', 'approved', 'rejected', 'refunded')),
    currency            char(3) NOT NULL DEFAULT 'ARS',
    subtotal            int NOT NULL CHECK (subtotal >= 0),
    total               int NOT NULL CHECK (total >= 0),
    pickup_location     text NOT NULL,
    customer_notes      text NOT NULL DEFAULT '' CHECK (length(customer_notes) <= 1000),
    cancellation_reason text NOT NULL DEFAULT '',
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    completed_at        timestamptz,
    cancelled_at        timestamptz
);

CREATE INDEX shop_orders_created_idx ON shop_orders (created_at DESC);
CREATE INDEX shop_orders_status_idx ON shop_orders (status, created_at DESC);
CREATE INDEX shop_orders_customer_idx ON shop_orders (lower(customer_email), created_at DESC);

CREATE TABLE shop_order_items (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id     uuid NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    product_id   uuid REFERENCES products(id) ON DELETE SET NULL,
    product_slug text NOT NULL,
    product_name text NOT NULL,
    sku          text NOT NULL,
    unit_price   int NOT NULL CHECK (unit_price >= 0),
    quantity     int NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    line_total   int NOT NULL CHECK (line_total = unit_price * quantity)
);

CREATE INDEX shop_order_items_order_idx ON shop_order_items (order_id);

CREATE TABLE shop_order_status_history (
    id         bigserial PRIMARY KEY,
    order_id   uuid NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    from_status text,
    to_status   text NOT NULL,
    note        text NOT NULL DEFAULT '',
    actor       text NOT NULL DEFAULT 'system',
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX shop_order_history_order_idx
    ON shop_order_status_history (order_id, created_at);

-- migrate:down

DROP TABLE IF EXISTS shop_order_status_history;
DROP TABLE IF EXISTS shop_order_items;
DROP TABLE IF EXISTS shop_orders;
DROP TABLE IF EXISTS shopping_cart_items;
DROP TABLE IF EXISTS shopping_carts;

DROP INDEX IF EXISTS products_shop_search_idx;
DROP INDEX IF EXISTS products_shop_listing_idx;
DROP INDEX IF EXISTS products_slug_unique;

ALTER TABLE products
    DROP CONSTRAINT IF EXISTS products_slug_format,
    DROP COLUMN IF EXISTS updated_at,
    DROP COLUMN IF EXISTS sort_order,
    DROP COLUMN IF EXISTS featured,
    DROP COLUMN IF EXISTS gallery,
    DROP COLUMN IF EXISTS image_url,
    DROP COLUMN IF EXISTS category_id,
    DROP COLUMN IF EXISTS short_description,
    DROP COLUMN IF EXISTS description,
    DROP COLUMN IF EXISTS slug;

DROP TABLE IF EXISTS product_categories;
